title: TheMassiveConspiracy
author: Peter Nugent
email: Peterfnugent@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
Wake up and learn the truth!!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
